### ISSUE TITLE
Cannot Start the plugin

### ISSUE THREAD

**Issue by ghost** [NeverWise/plugin.video.mtv.it#3]
On fresh install

`21:27:59 296638.781250 T:1297085424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name Util
                                            Traceback (most recent call last):
                                              File "/home/addons/plugin.video.mtv.it/default.py", line 3, in <module>
                                                from neverwise import Util
                                            ImportError: cannot import name Util
                                            -->End of Python script error report<--
21:27:59 296639.000000 T:1956615088   ERROR: GetDirectory - Error getting plugin://plugin.video.mtv.it/
21:27:59 296639.000000 T:1956615088   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mtv.it/) failed`

installed mtv.it plugin and script.module.neverwise

**Comment by NeverWise** [comment]
Unfortunately it seems that the streams of this addon have been encrypted.
I can view them with VLC but not with kodi.
I don't know if I will find a solution to the problem...

**Comment by Testato** [comment]
ma questo sembra solo un errore di importazione di Util, lo dice chiaramente il log
`Error Contents: cannot import name Util`

stessa cosa sul plugin fatto quotidiano
https://github.com/NeverWise/plugin.video.fattoquotidianotv/issues/2

**Comment by NeverWise** [comment]
Purtroppo questo plugin (insieme ad altri) non viene più mantenuto perché i contenuti non mi sembrano adeguati allo scopo per cui kodi è sviluppato.
