### ISSUE TITLE
Ad oggi non funziona +......

### ISSUE THREAD

**Issue by DjDiabolik** [NeverWise/plugin.video.mtv.it#4]
........ non sono espertissimo di Phyton però guardando il sito mtv.it è cambiato un pò il layer tant'è che la sezione ondemand è stata spostata ed ora ci si arriva direttamente dalla lista dei programmi.

Forse c'è solo da adattare il default.py ?

**Comment by NeverWise** [comment]
Purtroppo questo plugin (insieme ad altri) non viene più mantenuto perché i contenuti non mi sembrano adeguati allo scopo per cui kodi è sviluppato.

**Comment by DjDiabolik** [comment]
In che senso scusa ? Non mi sembra che l'addons interessi la pirateria....................

Per assurdo anche l'addons di youtube non dovrebbe essere adeguato......... è forse cambiato qualcosa nelle recenti versioni ?
Magari qualcosa è stato notificato anche ad altri addons nel forum ufficiale nella sezione dedicata agli addons ?

**Comment by NeverWise** [comment]
No, non interessa la pirateria ma la stragrande maggioranza dei contenuti non supera i 5 minuti di durata. Non è un problema di legalità ma di tempo che io devo spendere per contenuti che sono più da "casual entertainment" che da intrattenimento vero e proprio.

**Comment by DjDiabolik** [comment]
Ah ecco........ bè onestamente stiamo parlando di un'issue aperto nel 2017 quindi le cose saranno pure cambiate 3 anni dopo.

Cmq sia ancora oggi sul sito di MTV trovi per assurdo tutte le puntate di Mario di Maccio capatonda e quindi non dirrei che sono video di 5 minuti :)

Poi x carità...... la repository è tua e non saranno ne i primi ne gli ultimi addons non + sviluppati...... 
Alla fine è... e deve rimanere un'hobby quello dello sviluppo di un'addons........

*EDIT*
Poi la butto la.... l'addons dplay ad esempio. Ora c'è quel Dplay+ che se non è sbaglio è a pagamento e ci sono una marea di documentari di quelli che vanno in onda su Dmax.
